export const CONFIG = {
  // Public form submissions
  PUBLIC_SUBMIT_PER_HOUR: 10,
  MAX_BODY_BYTES: 64 * 1024,
  MAX_TEXT_LEN: 5000,

  // AI generation — TIERED QUOTAS
  AI_DAILY_QUOTA: 50,           // Regular users (safe limit)
  AI_DAILY_QUOTA_ADMIN: 200,    // Admins get more (trusted)

  PROMPT_MIN_LEN: 10,
  PROMPT_MAX_LEN: 3000,
  INSIGHTS_SAMPLE_SIZE: 50,

  // Forms
  FORMS_LIST_LIMIT: 100,
  TITLE_MAX_LEN: 200,
  DESCRIPTION_MAX_LEN: 2000,
  MAX_FIELDS: 200,
  MAX_CALCULATIONS: 50,
  SLUG_LEN: 8,
  SLUG_MAX_ATTEMPTS: 5,

  // Responses
  RESPONSES_PAGE_DEFAULT: 50,
  RESPONSES_PAGE_MAX: 200,

  // Auth
  JWKS_CACHE_MS: 60 * 60 * 1000,
  CLOCK_SKEW_SECONDS: 60,

  // Caching / TTLs
  PUBLIC_FORM_CACHE_SECONDS: 60,
  RATE_LIMIT_TTL_SECONDS: 3600,
  AI_QUOTA_TTL_SECONDS: 86400,
} as const;
